version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TodoListDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  todolist.api:
    image: ${DOCKER_REGISTRY-}todolistapi
    build:
      context: .
      dockerfile: Api/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=TodoListDb;Username=postgres;Password=postgres
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db

volumes:
  postgres_data: